title: Office.com/setup - How to setup office 365 with a product key
description: Microsoft365.com/setup is an official portal to activate and start your Microsoft 365 product including office apps, cloud services and other collaboration services. You’ll need to Sign In and enter Microsoft 365 product key.
